#! /bin/sh

sxhkd &
feh --bg-fill ~/.config/wall.png &
polybar example &
compton -b & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Hexchat desktop=^10
bspc rule -a Firefox desktop=^2
bspc rule -a Termite desktop=^1

hexchat &
firefox &
termite &
termite
