#! /bin/sh

sxhkd &
sh /home/opendata/rgb/coloursync.sh &
polybar example &
compton -b --config ~/.config/compton.conf & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config active_border_color \#2F343F
bspc config normal_border_color \#383C4A

bspc rule -a Gimp desktop=^8 follow=on state=floating
bspc rule -a Hexchat desktop=^10
bspc rule -a Firefox desktop=^2
bspc rule -a Termite desktop=^1

hexchat &
firefox &
termite &
termite
